name: Actualizar resumen del perfil de GitHub

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generar tarjetas de resumen
        uses: vn7n24fzkq/github-profile-summary-cards@v0.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
